package edu.kit.ipd.are.agentanalysis.impl.xplore.layer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import edu.kit.ipd.are.agentanalysis.impl.execution.AgentHelper;
import edu.kit.ipd.are.agentanalysis.port.hypothesis.IHypothesesSelection;
import edu.kit.ipd.are.agentanalysis.port.hypothesis.IHypothesesSet;
import edu.kit.ipd.are.agentanalysis.port.xplore.layer.ILayerEntry;
import edu.kit.ipd.are.agentanalysis.port.xplore.selection.ISelectionProvider;
import edu.kit.ipd.parse.luna.graph.IGraph;

final class LayerEntry implements ILayerEntry {
	private static final long serialVersionUID = -349086188573289109L;

	private transient Layer layer;
	private transient int entryNo;
	private transient IGraph inputGraph;
	private transient IGraph evaluatedGraph;

	private transient LayerEntry parent;

	private List<IHypothesesSet> hypotheses;
	private transient Map<List<IHypothesesSelection>, LayerEntry> nextLayerEntries = new HashMap<>();

	LayerEntry(Layer layer, int number, LayerEntry parent, IGraph input) {
		this.layer = layer;
		this.entryNo = number;
		this.inputGraph = input;
		this.parent = parent;
		var instance = this.layer.getAgent().getAgentInstance();
		logger.debug("Run analysis for " + this.layer + ", " + this.layer.getAgent());
		this.evaluatedGraph = AgentHelper.execute(this.inputGraph, instance);
		logger.debug("Finished analysis for " + this.layer + ", " + this.layer.getAgent());

		if (this.layer.getAgentWithHypotheses() != null) {
			this.hypotheses = this.layer.getAgentWithHypotheses().getHypothesesFromGraph(this.evaluatedGraph);
		}
	}

	public void explore(ISelectionProvider selectionProvider) {
		if (this.hypotheses == null && selectionProvider != null) {
			throw new UnsupportedOperationException("No hypotheses for " + this);
		}
		if (this.hypotheses == null) {
			// No hypotheses ..
			this.createNextBySelection(null);
			return;
		}
		if (this.hypotheses.isEmpty()) {
			logger.warn("No hypotheses were generated by " + this);
		}
		var selections = selectionProvider.findSelection(this.hypotheses);
		for (var selection : selections) {
			this.createNextBySelection(selection);
		}
	}

	@Override
	public List<IHypothesesSet> getHypotheses() {
		return this.hypotheses == null ? List.of() : new ArrayList<>(this.hypotheses);
	}

	public LayerEntry createNextBySelection(List<IHypothesesSelection> selection) {
		if (this.layer.getNext() == null) {
			throw new UnsupportedOperationException("This is a leaf ..");
		}

		if (selection == null && this.layer.getAgentWithHypotheses() == null) {
			return this.createNoHypothesesNext();
		}

		if (selection == null || selection.isEmpty()) {
			throw new UnsupportedOperationException("No selection provided");
		}

		return this.createHypothesesNext(selection);

	}

	private LayerEntry createNoHypothesesNext() {
		if (!this.nextLayerEntries.isEmpty()) {
			throw new UnsupportedOperationException("NoHypotheses LayerEntry already explored.");
		}
		var newEntry = (LayerEntry) this.layer.getNext().createEntry(this, this.evaluatedGraph.clone());
		this.nextLayerEntries.put(null, newEntry);
		return newEntry;
	}

	private LayerEntry createHypothesesNext(List<IHypothesesSelection> selection) {
		logger.debug("Appling selection " + selection + " @ " + this.layer);
		var resultGraph = this.inputGraph.clone();
		this.layer.getAgentWithHypotheses().applyHypothesesToGraph(resultGraph, selection);

		var newEntry = (LayerEntry) this.layer.getNext().createEntry(this, resultGraph);
		this.nextLayerEntries.put(selection, newEntry);
		return newEntry;
	}

	private List<IHypothesesSelection> findSelection(LayerEntry layerEntry) {
		for (var entry : this.nextLayerEntries.entrySet()) {
			if (entry.getValue() == layerEntry) {
				return entry.getKey() == null ? null : new ArrayList<>(entry.getKey());
			}
		}
		return null;
	}

	@Override
	public boolean isLeaf() {
		return this.layer.getNext() == null;
	}

	@Override
	public List<ILayerEntry> getChildren() {
		return new ArrayList<>(this.nextLayerEntries.values());
	}

	@Override
	public List<IHypothesesSelection> getSelectionsFromBefore() {
		return this.parent == null ? null : this.parent.findSelection(this);
	}

	@Override
	public ILayerEntry[] getPathToRoot() {
		List<ILayerEntry> pathToRoot = new ArrayList<>();
		pathToRoot.add(this);

		LayerEntry before = this.parent;
		while (before != null) {
			pathToRoot.add(before);
			before = before.parent;
		}
		return pathToRoot.toArray(ILayerEntry[]::new);
	}

	@Override
	public String toString() {
		return "LayerEntry [id=" + this.getId() + ", " //
				+ "agent=" + (this.layer.getAgent() == null ? null : this.layer.getAgent().getClass().getSimpleName()) + ", " //
				+ "selectionsFromBefore=" + this.getSelectionsFromBefore() + ", " //
				+ "hypotheses=" + this.getHypotheses() + ", " //
				+ "]";
	}

	@Override
	public String getId() {
		return this.layer.getAgent().getClass().getSimpleName() + "-" + this.entryNo;
	}

	@Override
	public String getAgent() {
		return this.layer.getAgent().getClass().getSimpleName();
	}
}
