package edu.kit.ipd.eagle.port.xplore.layer;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import edu.kit.ipd.eagle.port.IAgentSpecification;
import edu.kit.ipd.eagle.port.xplore.selection.ISelectionProvider;

/**
 * Defines a layer of the exploration process. A layer contains multiple layer entries. A layer represents one
 * {@link IAgentSpecification}.
 *
 * @author Dominik Fuchss
 *
 */
public interface ILayer {
    /**
     * The default logger for the layered exploration.
     */
    Logger logger = LoggerFactory.getLogger(ILayer.class);

    /**
     * Get the entries of this layer.
     *
     * @return the current entries of this layer
     */
    List<ILayerEntry> getEntries();

    /**
     * Start exploration by using an {@link ISelectionProvider}. This will create new LayerEntries in the next layer.
     *
     * @param selectionProvider the selection provider to use (may be {@code null} iff no hypotheses can be generated by
     *                          the agent of this layer)
     * @param parallel          indicator for parallel execution
     */
    void explore(ISelectionProvider selectionProvider, boolean parallel);
}
